[workspace]
members = [
    "aesm-client",
    "dcap-provider",
    "dcap-ql-sys",
    "dcap-ql",
    "enclave-runner",
    "fortanix-sgx-abi",
    "fortanix-sgx-tools",
	"native-tls-ext",
    "report-test",
    "rs-libc",
    "sgxs",
    "sgx-isa",
    "sgxs-loaders",
    "sgxs-tools"
]
exclude = ["examples"]
